default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quantified_self_development

test:
  <<: *default
  database: quantified_self_test

production:
  <<: *default
  database: quantified_self_production
  username: quantified_self
  password: <%= ENV['QUANTIFIED_SELF_DATABASE_PASSWORD'] %>
